name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install root dev dependencies (format)
        run: |
          npm ci

      - name: Format check (Prettier)
        run: |
          npm run format -- --check

      - name: Install app dependencies
        run: |
          cd src/random-with-friends
          npm ci

      - name: Lint app (ESLint)
        run: |
          cd src/random-with-friends
          npm run lint -- --max-warnings=0

      - name: Build app
        run: |
          cd src/random-with-friends
          npm run build

      - name: Install e2e dependencies
        run: |
          cd test/e2e
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright E2E (production build)
        env:
          PLAYWRIGHT_USE_PROD: '1'
          PLAYWRIGHT_BASE_URL: 'http://localhost:3000'
        run: |
          cd test/e2e
          npm test

      - name: Upload Playwright report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: test/e2e/playwright-report/*
