name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            src/random-with-friends/package-lock.json
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-

      - name: Install root dependencies
        run: npm ci

      - name: Format check
        run: npm run format -- --check
      - name: Install app dependencies
        run: |
          cd src/random-with-friends
          npm ci
      - name: Lint
        run: |
          cd src/random-with-friends
          npm run lint -- --max-warnings=0
      - name: Build
        run: |
          cd src/random-with-friends
          npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: src/random-with-friends/.next
          if-no-files-found: warn
          compression-level: 6
          overwrite: true
          include-hidden-files: true

  test-e2e:
    needs: lint-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: src/random-with-friends/.next
      - name: Install e2e dependencies
        run: |
          cd test/e2e
          npm ci
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-
      - name: Install Playwright Browsers
        run: |
          cd test/e2e
          npx playwright install --with-deps
      - name: Run E2E tests
        env:
          PLAYWRIGHT_USE_PROD: '1'
          PLAYWRIGHT_BASE_URL: 'http://localhost:3000'
        run: |
          cd test/e2e
          npm test
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: test/e2e/playwright-report/*
